### ISSUE TITLE
Failed to execute 

### ISSUE THREAD

**Issue by funeraload** [TheMagicalPoof/hackeroneparse#1]
Error when executing 

`First scanning... -Traceback (most recent call last):
  File "/home/user/tools/hackeroneparse/./hackeroneparse.py", line 308, in <module>
    main()
  File "/home/user/tools/hackeroneparse/./hackeroneparse.py", line 44, in main
    in_scope = InScopeParse(req.get_in_scope_json_data(handle))
  File "/home/funeral/tools/hackeroneparse/./hackeroneparse.py", line 295, in __init__
    self._row_to_final_data_(row_json_data)
  File "/home/user/tools/hackeroneparse/./hackeroneparse.py", line 300, in _row_to_final_data_
    json_data.json()['data']['team']['in_scope_assets']['edges']))
KeyError: 'data'`

**Comment by TheMagicalPoof** [comment]
> Error when executing
> 
> `First scanning... -Traceback (most recent call last): File "/home/user/tools/hackeroneparse/./hackeroneparse.py", line 308, in <module> main() File "/home/user/tools/hackeroneparse/./hackeroneparse.py", line 44, in main in_scope = InScopeParse(req.get_in_scope_json_data(handle)) File "/home/funeral/tools/hackeroneparse/./hackeroneparse.py", line 295, in __init__ self._row_to_final_data_(row_json_data) File "/home/user/tools/hackeroneparse/./hackeroneparse.py", line 300, in _row_to_final_data_ json_data.json()['data']['team']['in_scope_assets']['edges'])) KeyError: 'data'`

Yeah, this problem happened because of the hackerone service changed the parsing of data, i will try to fix it a bit later. Thanks for reporting the issue.
